CREATE TABLE "public".token (
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	BIN varchar,
	token varchar,
	exp BigInt,
  	nbf BigInt,
  	working Boolean);
ALTER TABLE "public".organization OWNER TO ps;Big